### ISSUE TITLE
Being able to add more fences

### ISSUE THREAD

**Issue by Lumisteria** [StardewModders/mod-ideas#353] opened 2019-10-05 19:39 UTC
I would like to add more fences instead of replacing them. It would be cool to have more types, they could follow the same "structure" as existing ones and maybe use the same values for durability as existing ones too if it makes it easier to add.

**Comment by Warilized** [comment] 2019-10-13 18:16
Fences is hard coded iirc, so you can't add more

**Comment by minervamaga** [comment] 2019-10-20 01:45
A framework similar to Json Assets might be able to do something like this.  Custom flooring, walls, and paths are also possible with a framework, fences should be possible.

**Comment by minervamaga** [comment] 2019-10-20 02:14
Duplicate of #20 , closing and merging.

**Closed by minervamaga** 2019-10-20 02:14 UTC
Labels: for: smapi, status: available
