### ISSUE TITLE
Useful Community Center

### ISSUE THREAD

**Issue by AndyAllanPoe** [StardewModders/mod-ideas#493] opened 2020-06-28 01:40 UTC
1. NPCs use the Community Center more for meetups and parties (Change in schedule and possible location-specific dialogue)
    a) Ability to hangout with npcs
2. Ability to use appliances and other objects:
   a) community storage
   b) minigames
   c) cooking and crafting skills
   d) others
3. Community Center Day (already in SVE!)
   a) NPCs can gift the player and other npcs (Already implemented by the Happy Birthday mod!)

**Comment by minervamaga** [comment] 2020-06-28 02:01
Duplicate of #406

**Closed by minervamaga** 2020-06-28 02:01 UTC
