### ISSUE TITLE
Misophonia Accessability

### ISSUE THREAD

**Issue by HazooToo** [StardewModders/mod-ideas#468] opened 2020-03-24 03:33 UTC
Two separate ideas. One for choosing a season besides Spring to start in. Doesn't seem likely, but would be nice. 

Second idea might be easier? Remove the sound of the farmer eating solid food. Misophonia is a condition where certain sounds trigger feelings of irrational anger. The most common trigger is the sound of someone eating loudly. I'm surviving off a liquid diet with my farmers, because the sound of them eating solid food makes me want to kick my laptop off a mountain. Thank you.

**Comment by Littlebigdough** [comment] 2020-03-28 02:31
hello im no modder but a tip is in the meantime whilst your waiting for someone to ppick up this idea you can go into options when in stardew and scrol down to sound volume and turn it off and there should be no more food eating sounds. There will still be music and footsteps and weather though. Hope this helps while your waiting :)

**Comment by HazooToo** [comment] 2020-03-28 02:57
Thanks for the reply. I do keep the volume pretty low, but it's hard to go
spelunking in the mines without other sounds. Luckily, until I can find a
permanent solution, I have milky strawberry juice, from one of my 300 other
mods! No idea which one, anymore, but it's cheap to buy from Gus and it
gives a bit over 100 energy per can. Best of all? No horrible crunching
sounds! Have a great night!

**Comment by jamespfluger** [comment] 2020-03-29 00:18
I can take on the Misophonia request, as I have other sounds that infuriate me. If there are any other sounds that you don't like, I can remove those as well.  
Can someone assign this to me and mark it as in-progress?

---

As for changing the starting season... I love the idea, but there are a lot of events that happen in each season that unlock certain areas. I think that changing the starting season wouldn't be too difficult, but there would be a lot of problems that come with it regarding quests, letters, events, etc. It's possible to do, but I don't have the knowledge to address that one.

_(You may want to split these two requests into separate issues in order to track the progress of each idea)_

**Comment by kdau** [comment] 2020-03-29 00:29
The seasons part seems to be a duplicate of #127 , so that should just leave the part you're doing.

**Comment by HazooToo** [comment] 2020-03-29 00:34
Oh my God I'm so excited! I didn't really think anyone would find it
important enough to bother with the noise, thanks so much for taking it on.
Luckily, the eating noise is the only one that aggravates me, so I hope it
will be easy for you. I'll separate this from the Seasonal idea. That one
always did feel really complicated, I agree. Maybe something that might
work out in a Stardew sequel or something!

**Comment by HazooToo** [comment] 2020-03-29 01:38
Also how do I mark as in-progress and assign people? Never used GitHub before.

**Comment by jamespfluger** [comment] 2020-04-04 16:34
@HazooToo I've got a release on Nexus!

Check out the [release on Nexus here](https://www.nexusmods.com/stardewvalley/mods/5691/) and let me know if this is or isn't what you were looking for.

Anyone can view the [source code on GitHub here](https://github.com/jamespfluger/Stardew-ModCollection)

**Comment by HazooToo** [comment] 2020-04-04 23:06
EXCITED! I'm downloading it now. Thank you so much!

**Comment by jamespfluger** [comment] 2020-04-06 21:49
This can be closed as complete. User has confirmed it is working.

**Closed** 2020-04-06 21:50 UTC
Labels: diff: hard, for: smapi, status: complete
