### ISSUE TITLE
completed community center made useful?

### ISSUE THREAD

**Issue by Hard2Borig** [StardewModders/mod-ideas#406] opened 2019-12-11 21:54 UTC
Have searched but haven't found a mod that makes the completed community center useful.  Ideas like the blacksmith area that actually works (maybe better output?) and coal bins that give a bit of coal.  fish tank that lets you add and see fish?  Kitchen that lets you cook, maybe has stuff in the fridge...  bookshelf with previously read books or new ones.  A safe that does... well, safey stuff....  that sort of thing.
I am amazed again and again at the stuff the Modders come up with.  The game wouldn't be the same without some of my favorites.  Thank you all for the great work and brilliant puzzle solving.

**Comment by GStefanowich** [comment] 2019-12-11 23:52
Possible duplicate of #347

**Closed** 2019-12-11 23:55 UTC
Labels: status: duplicate
