### ISSUE TITLE
Community Bundle/ Gift tastes with crops from PPJA

### ISSUE THREAD

**Issue by SugarWizard** [StardewModders/mod-ideas#440] opened 2020-01-20 23:16 UTC
Hi! I really love the variety of crops, fruit and recipes PPJA gives us. However, as it is they seem a bit isolated when they are not used for anything but selling. For this reason I would very much like a community bundle that includes PPJA and also for the villagers to have more tastes when it comes to the assets if this is at all possible. Thank you!

**Comment by minervamaga** [comment] 2020-01-20 23:44
Duplicate of #160

**Closed** 2020-01-20 23:45 UTC
Labels: status: duplicate
