### ISSUE TITLE
Event Limiter (no events in a row)

### ISSUE THREAD

**Issue by omena007** [StardewModders/mod-ideas#703] opened 2021-05-24 10:18 UTC
Hi everyone! I would absolutely love to have this type of mod since we all have probably encountered this problem that when you visit a map rarely you are faced with 3 in a row events when you finally do. It's really bad for immersion and storytelling when many unraleted and time spesific events happen in a row, not to mention a bit tiring to have them all at once. I confess I'm ignorant of the diffculty of this mod but I do think it's quite essential for the player experience (and I'm still wondering why this hasn't been done already, or has it?)

**Comment by itsbenter** [comment] 2021-06-13 04:14
I've suggested something similar a while ago but it seems no one into picking up the idea so far.
https://github.com/StardewModders/mod-ideas/issues/572

**Comment by Pathoschild** [comment] 2021-06-17 21:37
I'll close this as a duplicate of #572, but feel free to post there if you have any other suggestions for it!

**Closed by Pathoschild** 2021-06-17 21:37 UTC
Labels: status: duplicate
